use_frameworks!
platform :ios, '9.0'

target 'DDFeedback_Example' do
  pod 'DDFeedback', :path => '../'
  pod 'RxDataSources'
  target 'DDFeedback_Tests' do
    inherit! :search_paths

    
  end
end
